services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: luma-web
    ports:
      - "4005:4200"
    volumes:
      - ./web:/app
      - /app/node_modules
    stdin_open: true
    tty: true
