services:
  web:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: luma-web
    working_dir: /app
    volumes:
      - ./app:/app
      - flutter-pub-cache:/root/.pub-cache
    environment:
      - PUB_CACHE=/root/.pub-cache
    stdin_open: true
    tty: true
    command: bash

  apk:
    build:
      context: .
      dockerfile: docker/apk/Dockerfile
    container_name: luma-apk
    working_dir: /app
    volumes:
      - ./app:/app
      - flutter-pub-cache:/root/.pub-cache
      - gradle-cache:/root/.gradle
    environment:
      - PUB_CACHE=/root/.pub-cache
      - GRADLE_USER_HOME=/root/.gradle
    command: flutter build apk --split-per-abi
    profiles: ["apk"]

volumes:
  flutter-pub-cache:
  gradle-cache:
